version: '3'

volumes:
  db:

services:
  cli: 
    build: .
    depends_on:
      - mysql

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my
      - MYSQL_DATABASE=wasd
    
    volumes:
      - db:/var/lib/mysql
      - ./main.sql:/sql/main.sql
